config:
  space:
    width: 20.0
    height: 10.0

  centerline:
    n_points: 60
    max_lloyd_iterations: 10
    curvature_threshold: 0.3

  walls:
    duct_thickness: 0.30
    min_track_width: 3.00
    width_model:
      components:
        - type: constant
          value_dist:
            type: uniform
            low: 1.0
            high: 2.0

  output:
    visualize: false
    debug_output_dir: "debug"
    output_dir: "output"
